### ISSUE TITLE
Add a button for the mailing list

### ISSUE THREAD

**Issue by david-ma** [SkateCal/SkateCal.github.io#1]
I made a basic form to collect emails from people, we should add that to the webpage:

https://docs.google.com/forms/d/e/1FAIpQLSccWmO-RC0FACVGhFpmBysqG056AOMgZ2mbpYerNmCL6HQuhw/viewform?embedded=true

`<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSccWmO-RC0FACVGhFpmBysqG056AOMgZ2mbpYerNmCL6HQuhw/viewform?embedded=true" width="640" height="986" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>`

**Comment by axotol** [comment]
I've added the mailing list button
